# remap prefix to ctrl-a to not hate myself
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# mouse support
set -g mouse on

# vi mode
setw -g mode-keys vi
bind -T copy-mode-vi '#' send -X search-backward "#{copy_cursor_word}"
bind -T copy-mode-vi '*' send -X search-forward "#{copy_cursor_word}"

# match vim style splits, open in current path
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# start numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# faster escape (for vim)
set -sg escape-time 10

# more history
set -g history-limit 10000

# reload config
bind r source-file ~/.tmux.conf \; display "reloaded"
